#!/bin/bash

set -eu -o pipefail

if [ -e "/var/Containerfile" ]; then
   if [ ! -e "/var/.Containerfile" ]; then
     echo "Local modifications detected to os Containerfile"
     exit 1
   fi

   if cmp -s /var/Containerfile /var/.Containerfile; then
     echo "Local modifications detected to os Containerfile, changes made outside dnf-bootc"
     exit 2
   fi
fi

bootc usr-overlay || true
exec dnf --setopt=pluginpath=/var/dnf-plugins/ $*

