#!/bin/bash

set -eu -o pipefail

if [ "$EUID" -ne 0 ]; then
  echo "Error: This command has to be run with superuser privileges (under the root user on most systems)." >&2
  exit 1
fi

if [ -e "/var/Containerfile" ] && ! cmp -s /var/Containerfile /var/.Containerfile; then
  echo "Error: Local modifications detected to os Containerfile" >&2
  exit 2
fi

run_bootc_usr_overlay="true"
# Read and parse /proc/mounts
while read -r device mountpoint fstype options dump pass; do
  if [ "$device" = "overlay" ] && [ "$mountpoint" = "/usr" ]; then
    run_bootc_usr_overlay="false"
    break
  fi
done < /proc/mounts

if $run_bootc_usr_overlay; then
  bootc usr-overlay
fi

exec dnf --setopt=pluginpath=/var/dnf-plugins/ $*

