#!/bin/bash

set -eu -o pipefail

if [ "$EUID" -ne 0 ]; then
  echo "Error: This command has to be run with superuser privileges (under the root user on most systems)." >&2
  exit 1
fi

if [ -e "/var/Containerfile" ] && ! cmp -s /var/Containerfile /var/.Containerfile; then
  echo "Error: Local modifications detected to os Containerfile" >&2
  exit 2
fi

if ! grep -q "overlay /usr overlay" /proc/mounts; then
  bootc usr-overlay
fi

exec dnf --setopt=pluginpath=/var/dnf-plugins/ $*

